services:
  - type: web
    name: kidsmindful-backend
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: PORT
        value: 3000
      - key: DATABASE_URL
        value: ${DATABASE_URL}
    healthCheckPath: /api/health
    autoDeploy: true 